#!/bin/sh
# chkconfig: - 99 10
#
#       /etc/rc.d/init.d/<servicename>
#
#       <description of the *service*>
#       <any general comments about this init script>
#
# <tags -- see below for tag definitions.  *Every line* from the top
#  of the file to the end of the tags section must begin with a #
#  character.  After the tags section, there should be a blank line.
#  This keeps normal comments in the rest of the file from being
#  mistaken for tags, should they happen to fit the pattern.>
#
# sudo chmod 755 /etc/init.d/datanode
# sudo chkconfig --level 345 datanode on
# Source function library.

touch /var/lock/hadoop
export HADOOP_CLASSPATH=/opt/hadoop/lib/*.jar
export HADOOP_HOME=/opt/hadoop
export PATH=$PATH:$HADOOP_HOME/bin
export PATH=$PATH:$HADOOP_HOME/sbin
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib"
export HADOOP_PREFIX=/opt/hadoop
export JAVA_HOME=/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b11.el7.arm/jre
DESC="datanode startup"
DAEMON="datanode"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    su - hdfs -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR --script hdfs start datanode"
    echo "Starting datanode"
    ;;
  stop)
    su - hdfs -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR --script hdfs stop datanode"
    rm /var/lock/hadoop
    echo "stopping"
    ;;
  *)
    echo "Usage: start|stop"
    exit 1
    ;;
esac

exit 0
