#!/bin/bash
# chkconfig: - 99 10
#
#	/etc/rc.d/init.d/<servicename>
#
#	<description of the *service*>
#	<any general comments about this init script>
#
# <tags -- see below for tag definitions.  *Every line* from the top
#  of the file to the end of the tags section must begin with a #
#  character.  After the tags section, there should be a blank line.
#  This keeps normal comments in the rest of the file from being
#  mistaken for tags, should they happen to fit the pattern.>

# Source function library.
export HADOOP_OPTS=-Djava.library.path=/opt/hadoop/lib
export JAVA_HOME=/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64/jre
export PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/hadoop/bin:/opt/hadoop/sbin:/opt/spark/bin:/home/hdfs/.local/bin:/home/hdfs/bin
export HADOOP_HDFS_HOME=/opt/hadoop
export HADOOP_COMMON_HOME=/opt/hadoop
export HADOOP_PREFIX=/opt/hadoop
export HADOOP_CLASSPATH=/opt/hadoop/lib/*.jar
export HADOOP_HOME=/opt/hadoop
export PATH=$PATH:$HADOOP_HOME/bin
export PATH=$PATH:$HADOOP_HOME/sbin
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib"
DESC="namenode startup"
DAEMON="namenode"

. /etc/init.d/functions

#define any local shell functions used by the code that follows

start() {
	echo -n "Starting namenode: "
	su - hdfs -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR --script hdfs start namenode"
	touch /var/lock/subsys/namenode
	return 0
}	

stop() {
	echo -n "Shutting down namenode: "
	su - hdfs -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR --script hdfs stop namenode"
	rm -f /var/lock/subsys/namenode
	return 0
}

case "$1" in
    start)
         start
	 ;;
    stop)
        stop
	;;
    status)
	
	;;
    restart)
         stop
	 start
	 ;;
    *)
	echo "Usage: namenode {start|stop|status|reload|restart[|probe]"
	exit 1
	;;
esac
exit $?

